export const supplierFields = () => {
    return [
        {
            name: 'legalCompanyNameEn',
            label: 'legalCompanyNameEn',
            placeholder: 'legalCompanyNameEn',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'legalCompanyNameAr',
            label: 'legalCompanyNameAr',
            placeholder: 'legalCompanyNameAr',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'countryCode',
            label: 'countryCode',
            placeholder: 'countryCode',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'city',
            label: 'city',
            placeholder: 'city',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'phoneNumber',
            label: 'phoneNumber',
            placeholder: 'phoneNumber',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'email',
            label: 'Email',
            placeholder: 'Email',
            colSpan: 'col-span-6',
            type: 'email',
            required: true,
        },
        {
            name: 'commercialRegistrationNumber',
            label: 'commercialRegistrationNumber',
            placeholder:
                'commercialRegistrationNumber',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'taxCertificateNumber',
            label: 'taxCertificateNumber',
            placeholder:
                'taxCertificateNumber',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'tourismLicenseNumber',
            label: 'tourismLicenseNumber',
            placeholder:
                'tourismLicenseNumber',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'bankIban',
            label: 'bankIban',
            placeholder: 'bankIban',
            colSpan: 'col-span-6',
            type: 'text',
            required: true,
        },
        {
            name: 'contractEndDate',
            label: 'contractEndDate',
            placeholder: 'contractEndDate',
            colSpan: 'col-span-6',
            type: 'date',
            required: true,
        },

        {
            type: "spacer",
            colSpan: 'col-span-4',
        },

        // Owner
        {
            name: 'owner.name',
            label: 'owner.name',
            placeholder: 'owner.name',
            colSpan: 'col-span-4',
            type: 'text',
            required: true,
        },
        {
            name: 'owner.phoneNumber',
            label: 'owner.phoneNumber',
            placeholder:
                'owner.phoneNumber',
            colSpan: 'col-span-4',
            type: 'text',
            required: true,
        },
        {
            name: 'owner.email',
            label: 'owner.email',
            placeholder: 'owner.email',
            colSpan: 'col-span-4',
            type: 'email',
            required: true,
        },

        // Documents
        {
            name: 'documents.commercialRegistrationUploadId',
            label: 'documents.commercialRegistration',
            colSpan: 'col-span-6',
            type: 'upload',
            required: true,
            uploadCategory: 'commercial_registration',
        },
        {
            name: 'documents.taxCertificateUploadId',
            label: 'documents.taxCertificate',
            colSpan: 'col-span-6',
            type: 'upload',
            required: true,
            uploadCategory: 'tax_certificate',
        },
        {
            name: 'documents.tourismLicenseUploadId',
            label: 'documents.tourismLicense',
            colSpan: 'col-span-6',
            type: 'upload',
            required: true,
            uploadCategory: 'tourism_license',
        },
        {
            name: 'documents.supplierContractUploadId',
            label: 'documents.supplierContract',
            colSpan: 'col-span-6',
            type: 'upload',
            required: true,
            uploadCategory: 'supplier_contract',
        },
        {
            name: 'documents.companyOwnerIdUploadId',
            label: 'documents.companyOwnerId',
            colSpan: 'col-span-6',
            type: 'upload',
            required: true,
            uploadCategory: 'company_owner_id',
        },
        {
            name: 'documents.bankGuaranteeLetterUploadId',
            label: 'documents.bankGuaranteeLetter',
            colSpan: 'col-span-6',
            type: 'upload',
            required: true,
            uploadCategory: 'bank_guarantee_letter',
        },

        // {
        //   name: 'documents.commercialRegistrationUploadId',
        //   label:
        //     'documents.commercialRegistration',
        //   colSpan: 'col-span-6',
        //   type: 'upload',
        //   required: true,
        // },
        // {
        //   name: 'documents.taxCertificateUploadId',
        //   label: 'documents.taxCertificate',
        //   colSpan: 'col-span-6',
        //   type: 'upload',
        //   required: true,
        // },
        // {
        //   name: 'documents.tourismLicenseUploadId',
        //   label: 'documents.tourismLicense',
        //   colSpan: 'col-span-6',
        //   type: 'upload',
        //   required: true,
        // },
        // {
        //   name: 'documents.supplierContractUploadId',
        //   label: 'documents.supplierContract',
        //   colSpan: 'col-span-6',
        //   type: 'upload',
        //   required: true,
        // },
        // {
        //   name: 'documents.companyOwnerIdUploadId',
        //   label: 'documents.companyOwnerId',
        //   colSpan: 'col-span-6',
        //   type: 'upload',
        //   required: true,
        // },
        // {
        //   name: 'documents.bankGuaranteeLetterUploadId',
        //   label:
        //     'documents.bankGuaranteeLetter',
        //   colSpan: 'col-span-6',
        //   type: 'upload',
        //   required: true,
        // },
    ];
};